version: '2'
services:
  mongo:
    container_name: ocl_mongo
    image: mongo
  redis:
    container_name: ocl_redis
    image: redis
  solr:
    build:
      context: ../../
      dockerfile: ./django-nonrel/ocl/Dockerfile.solr
    container_name: ocl_solr
    ports:
      - "8983:8983"
  ocl:
    container_name: ocl_api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash startup_showcase.sh
    depends_on:
      - mongo
      - solr
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  ocl_worker:
    container_name: ocl_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: bash run_celery.sh
    depends_on:
      - mongo
      - solr
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
    volumes:
      - .:/code
    environment:
      - C_FORCE_ROOT=1
