version: '2'
services:
  mongo:
    container_name: ocl_mongo
    image: mongo
    ports:
      - "27017:27017"
  solr:
    build:
      context: ../../
      dockerfile: ./django-nonrel/ocl/Dockerfile.solr
    container_name: ocl_solr
    ports:
      - "8983:8983"
  ocl:
    container_name: ocl_api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash startup_showcase.sh
    depends_on:
      - mongo
      - solr
    links:
      - "mongo:mongo.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
    ports:
      - "8000:8000"
    volumes:
      - .:/code

